# fly.toml app configuration file generated for breez-nodeless-api on 2025-06-02T20:49:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'breez-nodeless-api'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[[mounts]]
  source = 'breez_data'
  destination = '/app/tmp'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

  [http_service.http_options]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
